spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

rabbitmq:
  host: ${RABBIT_HOST}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
  exchanges:
    internal: internal.exchange
  queues:
    internal: internal.queue
  routing-keys:
    internal: internal.routing-key

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}