spring:
  config:
    activate:
      on-profile: dev

rabbitmq:
  host: ${RABBIT_HOST}
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
  exchanges:
    feedback: feedback.exchange
    internal: internal.exchange
  queues:
    feedback: feedback.queue
    internal: internal.queue
  routing-keys:
    feedback: feedback.routing-key
    internal: internal.routing-key

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}